[project]
name = "hoshiko"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cachetools>=6.2.0",
    "discord>=2.3.2",
    "jikanpy-v4>=1.0.2",
    "niquests>=3.15.2",
]
